### Linux Fast Path Bug Patches ###
<table>
 <thead>
    <tr>
     <td>Title</td>
     <td>Category</td>
     <td>Why is this a Fast Path Bug?</td>
     <td>Which lines cause the bug?</td>
    </tr>
    </thead>
   <tbody>
<tr><td><font size=+1><b>1:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=cbef8478bee55775ac312a574aad48af7bb9cf9f">pmd_huge() returns true for non-present hugepage</a></td><td>RET</td><td> This bug occurs in both fast path and slow path, and stems from an incorrect return value on some conditional branches</td><td> Multiple (both fast and slow path functions)</td></tr>
<tr><td><font size=+1><b>2:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=d7365e783edb858279be1d03f61bc8d5d3383d90">fix missed end-writeback page accounting</a></td><td>Path State</td><td> The file unmap fast path is missing the function call to check if the page is still charged.</td><td> The bug is triggered at L2353 in page-writeback.c (test_clear_page_writeback), but the cause of the bug is extensive (throughout the uncharge and writeback functions)</td></tr>
<tr><td><font size=+1><b>3:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=eadb41ae82f802105c0601aa8a0a0e7595826497">prevent walking off the end of a pagetable in no-pmd configuration</a></td><td>Path State</td><td>  The fast path returns an incorrect range for configurations with folded pmd</td><td> L379 (__munlock_pagevec_fill)</td></tr>
<tr><td><font size=+1><b>4:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm?id=49255c619fbd482d704289b5eb2795f8e3b7ff2e">move check for disabled anti-fragmentation out of fastpath</a></td><td>CON</td><td> This damages performance in the fast path with a condition that is unlikely to occur there.</td><td>  L168</td></tr>
<tr><td><font size=+1><b>5:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs?id=ce170828e24959c69e7a40364731edc0535c550f">fix disk file size and memory file size mismatch</a></td><td>RET</td><td> File size is unchanged in fast path, need to skip fast path in order to ensure correct file size is returned</td><td>  L2167</td></tr>
<tr><td><font size=+1><b>6:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs?id=260a459d2e39761fbd39803497205ce1690bc7b1">Is mounted should be testing mnt_ns for NULL or error.</a></td><td>Path State</td><td>  Incorrect value is being checked in fast path</td><td> L74</td></tr>
<tr><td><font size=+1><b>7:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs?id=f55aa59106b66cd547c8f296e0b3430ad76554c5">fix bug where page is marked uptodate when out of space</a></td><td>FAU</td><td>  A page can be marked up to date in FP and then fail when there's not enough space, with no handler in slowpath.</td><td> Multiple</td></tr>
<tr><td><font size=+1><b>8:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs?id=b09e593d799560f1a0782c20ac5900058390a26f">Fix a ref count bug and other clean ups</a></td><td>RET</td><td>"  Incorrect ref count in fast path
"</td><td> Multiple</td></tr>
<tr><td><font size=+1><b>9:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/drivers?id=b0b477c7e0dd93f8916d106018ded1331b81bf61">use percpu 'repeat_count' and 'current_path'</a></td><td>FAU</td><td>  If this fast path fails while it is 'current_path', there is no fault handler.</td><td> Multiple</td></tr>
<tr><td><font size=+1><b>10:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/drivers?id=1c63dc66580d4bbb6d2b75bf184b5aa105ba5bdb">split a new struct nvme_ctrl out of struct nvme_dev</a></td><td>ADS</td><td>  Unecessary values being used in/out of the I/O fast path</td><td> Multiple</td></tr>
<tr><td><font size=+1><b>11:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/drivers?id=bc602280871cdedc906f622b036f5799f16c13c2">Move TxFIFO underrun handling to reset path</a></td><td>FAU</td><td>  Allow fault handling outside of the fast path</td><td> Optimization</td></tr>
<tr><td><font size=+1><b>12:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/drivers?id=2f6ae5cd24491647a011aead90d47523d875e443">only allow REQ_TYPE_FS to use fast path</a></td><td>FAU</td><td>  Missing fault handler for fast path failure</td><td>  L2330</td></tr>
<tr><td><font size=+1><b>13:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/drivers?id=c130480b129fbfd7932ad7af3f4ffcea630b027f">Fix se_cmd->state_list leak regression during WRITE failure</a></td><td>FAU</td><td> Failure during WRITE can spill over into fast path</td><td>  L2134</td></tr>
<tr><td><font size=+1><b>14:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/drivers?id=bab6a9eac05360db25c81b0090f6b1195dd986cc">Fix setting initial MAC address</a></td><td>Path State</td><td> Incorrect fast path implementation created regression</td><td> L411</td></tr>
<tr><td><font size=+1><b>15:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/drivers?id=d4aeee776017b6da6dcd12f453cd82a3c951a0dc">Disable pagefaults along execbuffer relocation fast path</a></td><td>FAU</td><td>  A potential circular lock dependancy bug that is unhandled in fast path</td><td> L444</td></tr>
<tr><td><font size=+1><b>16:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/drivers?id=dc187cb381f1bceb30498861ece510245c43ed9f">Update firmware and version</a></td><td>Path State</td><td> Outdated context in fast path</td><td>  L56</td></tr>
<tr><td><font size=+1><b>17:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/drivers?id=9fd5746fd3d7838bf6ff991d50f1257057d1156f">Remove i_cindex from struct inode</a></td><td>ADS</td><td>  Unnecessary data structure values passing into fast path, specifically i_cindex.</td><td>  L156</td></tr>
<tr><td><font size=+1><b>18:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/drivers?id=51d2bfbddb33dc59786a3a41f7eeb59e30fa561c">Move ehca2ib_return_code() out of line</a></td><td>RET</td><td> Inlined slowpath code</td><td> Optimization</td></tr>
<tr><td><font size=+1><b>19:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/drivers?id=8f140b407f3be04e7202be9aa0cfef3006d14c9f">Shadow the gpio_mask register</a></td><td>CON</td><td> Out of date code creates unecessary fast path call</td><td> Optimization</td></tr>
<tr><td><font size=+1><b>20:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/net?id=dc327f8931cb9d66191f489eb9a852fc04530546">close another race condition in tcf_mirred_release()</a></td><td>Path State</td><td> Lock reduction creating race condition in fast path</td><td> Multiple</td></tr>
<tr><td><font size=+1><b>21:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/net?id=c2f34a65a61cd1ace3b53c93e8b38d2f79f4ff0d">fix potential NULL deref in __inet_inherit_port()</a></td><td>FAU</td><td>  Unhandled Race condition in fast path</td><td>  Multiple</td></tr>
<tr><td><font size=+1><b>22:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/net?id=d64d80a2cde94f3e89caebd27240be419fec5b81">don't extract flow keys on early demuxed sks in socket match</a></td><td>CON</td><td>  Unnecessary values being accessed in fast path</td><td> Multiple</td></tr>
<tr><td><font size=+1><b>23:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/net?id=76fecd8275be6de76513430e7526825944ab932f">In mpls_egress verify the packet length.</a></td><td>FAU/RET</td><td>  Failing to confirm byte presence in fast path</td><td> L92</td></tr>
<tr><td><font size=+1><b>24:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/net?id=c5c6a8ab45ec0f18733afb4aaade0d4a139d80b3">add key management to congestion control</a></td><td>ADS</td><td> Optimizes fast path by caching precalculated key</td><td> Optimization</td></tr>
<tr><td><font size=+1><b>25:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/net?id=971f10eca186cab238c49daa91f703c5a001b0b1">better TCP_SKB_CB layout to reduce cache line misses</a></td><td>ADS</td><td> Bad list structure in fast path</td><td> Multiple</td></tr>
<tr><td><font size=+1><b>26:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/net?id=b13d3cbfb8e8a8f53930af67d1ebf05149f32c24">move eviction of queues to work queue</a></td><td>ADS</td><td> Moving queue eviction out of fast path</td><td> Optimization</td></tr>
<tr><td><font size=+1><b>27:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/net?id=3d4405226d27b3a215e4d03cfa51f536244e5de7">avoid dependency of net_get_random_once on nop patching</a></td><td>ADS</td><td>  Reorganizes fast path and slow path structure</td><td>  Optimization</td></tr>
<tr><td><font size=+1><b>28:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/net?id=2519a602c273c5254781bc55b6e678a17e469a12">optimize tcf_match_indev()</a></td><td>Path State</td><td> Incorrect search method and potential inconsistency in fast path function call</td><td>  Multiple</td></tr>
<tr><td><font size=+1><b>29:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/net?id=ef209f15980360f6945873df3cd710c5f62f2a3e">fix access the unallocated memory in netprio cgroup</a></td><td>Path State</td><td>  Fixing out of bound accesses in fast path</td><td>  Multiple</td></tr>
<tr><td><font size=+1><b>30:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/net?id=bb9fc37358ffa9de1cc2b2b6f1a559b926ef50d9">wrong multiplication of TCPOLEN_TSTAMP_ALIGNED in tcp_sack skips fastpath</a></td><td>CON</td><td>  Incorrect multiplication skips fast path</td><td>  L447</td></tr>
<tr><td><font size=+1><b>31:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/net?id=bdc712b4c2baf9515887de3a52e7ecd89fafc0c7">Decrease overhead of on-stack inet_cork.</a></td><td>ADS</td><td>  Splitting inet_cork into two structs, one for fast path</td><td> Optimization</td></tr>
<tr><td><font size=+1><b>32:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/net?id=8587523640441a9ff2564ebc6efeb39497ad6709">Check rps_flow_table when RPS map length is 1</a></td><td>CON</td><td>  Missing check for fast path</td><td>  L2563</td></tr>
<tr><td><font size=+1><b>33:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/net?id=767dd03369ac18af58efdef0383d6eb986eab426">speedup sock_recv_ts_and_drops()</a></td><td>CON</td><td>  Slow function in fast path</td><td></td></tr>
<tr><td><font size=+1><b>34:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/net?id=5007392d8512e666107dc356d4c2e05627b9029b">FIX ipv6_forward sysctl restart</a></td><td>FAU</td><td>  Fault in fast path leaks to userspace</td><td> L503 addrconf.c</td></tr>
<tr><td><font size=+1><b>35:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/net?id=6f74651ae626ec672028587bc700538076dfbefb">Seperate DSACK from SACK fast path</a></td><td>CON</td><td> Unnecessary check in fast path</td><td></td></tr>
<tr><td><font size=+1><b>36:</b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/net?id=2ad41065d9fe518759b695fc2640cf9c07261dd2">Clear stale pred_flags when snd_wnd changes</a></td><td>Path State</td><td>  Stale values in fast path</td><td> L2239 </td></tr>
   </tbody>
</table>

### Linux Patches in Fast Path Code ###
<table>
 <thead>
     <tr>
     <td>Title</td>
     <td>Category</td>
    </tr>
    </thead>
   <tbody>
<tr><td><font size=+1><b>1: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/slub.c?id=77c5e2d01af871f4bfbe08feefa3d5118cb1001b">slub: fix object tracking</a></td><td>ADS</td></tr>
<tr><td><font size=+1><b>2: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/slub.c?id=70d71228af9360cc4a0198ecd6351a1b34fa6d01">slub: remove object activities out of checking functions</a></td><td>CON / Path State</td></tr>
<tr><td><font size=+1><b>3: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/slub.c?id=272c1d21d6fe42979068e14c04fb60fb6045ad74">SLUB: return ZERO_SIZE_PTR for kmalloc(0)</a></td><td> Path State/ RET</td></tr>
<tr><td><font size=+1><b>4: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/slub.c?id=d07dbea46405b37d59495eb4de9d1056dcfb7c6d">Slab allocators: support __GFP_ZERO in all allocators</a></td><td>Path State</td></tr>
<tr><td><font size=+1><b>5: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/slub.c?id=ce15fea8274acca06daa1674322d37a7d3f0036b">SLUB: Do not use length parameter in slab_alloc()</a></td><td>ADS</td></tr>
<tr><td><font size=+1><b>6: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/slub.c?id=7fd272550bd43cc1d7289ef0ab2fa50de137e767">Avoid double memclear() in SLOB/SLUB</a></td><td>Path State</td></tr>
<tr><td><font size=+1><b>7: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/slub.c?id=00e962c5408b9f2d0bebd2308673fe982cb9a5fe">Revert "SLUB: Alternate fast paths using cmpxchg_local"</a></td><td>RET / FAU</td></tr>
<tr><td><font size=+1><b>8: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/slub.c?id=e72e9c23ee025a4c063ca112ba0a6059f9ecc9b7">Revert "SLUB: remove useless masking of GFP_ZERO"</a></td><td>Path State</td></tr>
<tr><td><font size=+1><b>9: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/slub.c?id=bdb21928512a860a60e6a24a849dc5b63cbaf96a">slub: Fix use-after-preempt of per-CPU data structure</a></td><td>ADS / FAU</td></tr>
<tr><td><font size=+1><b>10: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/slub.c?id=89124d706db0aa95daacfa4c0df45a43a44d44f4">slub: Add might_sleep_if() to slab_alloc()</a></td><td>Path State / CON</td></tr>
<tr><td><font size=+1><b>11: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/memcontrol.c?id=7f4d454dee2e0bdd21bafd413d1c53e443a26540">avoid deadlock caused by race between oom and cpuset_attach</a></td><td>FAU</td></tr>
<tr><td><font size=+1><b>12: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/page_alloc.c?id=327c0e968645f2601a43f5ea7c19c7b3a5fa0a34">fix it to take care of nodemask</a></td><td>ADS</td></tr>
<tr><td><font size=+1><b>13: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/memcontrol.c?id=81d39c20f5ee2437d71709beb82597e2a38efbbc">fix shrinking memory to return -EBUSY by fixing retry algorithm</a></td><td>RET / CON</td></tr>
<tr><td><font size=+1><b>14: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/memcontrol.c?id=0b7f569e45bb6be142d87017030669a6a7d327a1">fix OOM killer under memcg</a></td><td>ADS / FAU</td></tr>
<tr><td><font size=+1><b>15: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/memcontrol.c?id=a8031cb00e286600ea08bd00a6812dbfec412376">remove warning when CONFIG_DEBUG_VM=n</a></td><td>Path State</td></tr>
<tr><td><font size=+1><b>16: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/memcontrol.c?id=46f7e602fb32e02145ef14f8c0ca6d399f0a96b9">fix build warning and avoid checking for mem != null again and again</a></td><td>Path State</td></tr>
<tr><td><font size=+1><b>17: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/slub.c?id=7e85ee0c1d15ca5f8bff0f514f158eba1742dd87">slab,slub: don't enable interrupts during early boot</a></td><td>Path State</td></tr>
<tr><td><font size=+1><b>18: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/page_alloc.c?id=945a11136ebdfa7fcce319ee6215958e84cb85f6">add gfp mask checking for __get_free_pages()</a></td><td>RET</td></tr>
<tr><td><font size=+1><b>19: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/memcontrol.c?id=4e649152cbaa1aedd01821d200ab9d597fe469e4">some modification to softlimit under hierarchical memory reclaim.</a></td><td>RET / ADS</td></tr>
<tr><td><font size=+1><b>20: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/slub.c?id=74e2134ff892ee4ea4fbd52637060b71e540faf1">SLUB: Fix __GFP_ZERO unlikely() annotation</a></td><td>CON</td></tr>
<tr><td><font size=+1><b>21: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/slub.c?id=0f24f1287a86b198c1e4bd4ce45e8565e40ff804">tracing, slab: Define kmem_cache_alloc_notrace ifdef CONFIG_TRACING</a></td><td>RET / CON</td></tr>
<tr><td><font size=+1><b>22: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/page_alloc.c?id=4365a5676fa3aa1d5ae6c90c22a0044f09ba584e">fix NUMA constraint check with nodemask</a></td><td>CON</td></tr>
<tr><td><font size=+1><b>23: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/memcontrol.c?id=8033b97c9b5ef063e3f4bf2efe1cd0a22093aaff">avoid oom during moving charge</a></td><td>ADS</td></tr>
<tr><td><font size=+1><b>24: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/memcontrol.c?id=867578cbccb0893cc14fc29c670f7185809c90d6">fix oom kill behavior</a></td><td>FAU</td></tr>
<tr><td><font size=+1><b>25: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/memcontrol.c?id=93d5c9be1ddd57d4063ce463c9ac2be1e5ee14f1">fix prepare migration</a></td><td>RET / ADS</td></tr>
<tr><td><font size=+1><b>26: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/memcontrol.c?id=747388d78a0ae768fd82b55c4ed38aa646a72364">fix css_is_ancestor() RCU locking</a></td><td>Path State/ CON</td></tr>
<tr><td><font size=+1><b>27: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/page_alloc.c?id=c0ff7453bb5c7c98e0885fb94279f2571946f280">fix no node to alloc memory when changing cpuset's mems</a></td><td>ADS</td></tr>
<tr><td><font size=+1><b>28: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/memcontrol.c?id=b1dd693e5b9348bd68a80e679e03cf9c0973b01b">avoid deadlock between move charge and try_charge()</a></td><td>RACE</td></tr>
<tr><td><font size=+1><b>29: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/?id=ebb76ce16daf6908dc030dec1c00827d37129fe5&context=40&ignorews=0&dt=0">fix wrong VM_BUG_ON() in try_charge()'s mm->owner check</a></td><td>RET / CON</td></tr>
<tr><td><font size=+1><b>30: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/memcontrol.c?id=dfe076b0971a783469bc2066e85d46e23c8acb1c">fix deadlock between cpuset and memcg</a></td><td>RACE</td></tr>
<tr><td><font size=+1><b>31: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/page_alloc.c?id=f33261d75b88f55a08e6a9648cef73509979bfba">fix deferred congestion timeout if preferred zone is not allowed</a></td><td>CON</td></tr>
<tr><td><font size=+1><b>32: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/memcontrol.c?id=8dba474f034c322d96ada39cb20cac711d80dcb2">fix uninitialized variable use in mem_cgroup_move_parent()</a></td><td>Path State/ ADS</td></tr>
<tr><td><font size=+1><b>33: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/slub.c?id=b3d41885d9cd0d9db31c8f49e362bae02c96fa3f">slub: fix kmemcheck calls to match ksize() hints</a></td><td>RET</td></tr>
<tr><td><font size=+1><b>34: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/memcontrol.c?id=7ec99d6213b579a84c85ad37f2aa8ded4857c53c">unify charge/uncharge quantities to units of pages</a></td><td>RET / Path State</td></tr>
<tr><td><font size=+1><b>35: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/page_alloc.c?id=a197b59ae6e8bee56fcef37ea2482dc08414e2ac">fail GFP_DMA allocations when ZONE_DMA is not configured</a></td><td>Path State</td></tr>
<tr><td><font size=+1><b>36: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/slub.c?id=49a78d085fa6b44d6ed791923c7172a6433589c2">slub: remove no-longer used 'unlock_out' label</a></td><td>Path State</td></tr>
<tr><td><font size=+1><b>37: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/page_alloc.c?id=1fa7b6a29c61358cc2ca6f64cef4aa0e1a7ca74c">Revert "mm: fail GFP_DMA allocations when ZONE_DMA is not configured"</a></td><td>Path State</td></tr>
<tr><td><font size=+1><b>38: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/slub.c?id=d6543e3935cec9f66b9647c24c2e44c68f8a91fd">slub: Enable backtrace for create/delete points</a></td><td>ADS / FAU</td></tr>
<tr><td><font size=+1><b>39: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/slub.c?id=73736e0387ba0e6d2b703407b4d26168d31516a7">slub: fix a possible memleak in __slab_alloc()</a></td><td>"Path State
/ CON / FAU"</td></tr>
<tr><td><font size=+1><b>40: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/?id=b121186ab1b12e2a96a945d88eae0735b4542158&context=40&ignorews=0&dt=0">correct page->pfmemalloc to fix deactivate_slab regression</a></td><td> Path State</td></tr>
<tr><td><font size=+1><b>41: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/slub.c?id=8ba00bb68a067c221cc3ea3a0293e8fcbdcb7ba1">slub: consider pfmemalloc_match() in get_partial_node()</a></td><td>ADS / RET</td></tr>
<tr><td><font size=+1><b>42: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/page_alloc.c?id=d95ea5d18e699515468368415c93ed49b1a3221b">fix watermark checking</a></td><td> Path State</td></tr>
<tr><td><font size=+1><b>43: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/slub.c?id=4d7868e6475d478172581828021bd8a356726679">slub: Do not dereference NULL pointer in node_match</a></td><td>RET / CON</td></tr>
<tr><td><font size=+1><b>44: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/memcontrol.c?id=a0d8b00a3381f9d75764b3377590451cb0b4fe41">do not declare OOM from __GFP_NOFAIL allocations</a></td><td>CON /  Path State/ FAU</td></tr>
<tr><td><font size=+1><b>45: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/memcontrol.c?id=1f14c1ac19aa45118054b6d5425873c5c7fc23a1">do not allow task about to OOM kill to bypass the limit</a></td><td>FAU</td></tr>
<tr><td><font size=+1><b>46: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/mm/page_alloc.c?id=91fbdc0f89807bb97792ea6893717a8d3154b871">__alloc_pages_nodemask(): don't alter arg gfp_mask</a></td><td>ADS/ Path State</td></tr>
<tr><td><font size=+1><b>47: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs/inode.c?id=261bca86ed4f7f391d1938167624e78da61dcc6b">nfsd/create race fixes, infrastructure</a></td><td>ADS / RET</td></tr>
<tr><td><font size=+1><b>48: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs/inode.c?id=72a43d63cb51057393edfbcfc4596066205ad15d">ext3/4 with synchronous writes gets wedged by Postfix</a></td><td>ADS / Path State</td></tr>
<tr><td><font size=+1><b>49: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs/btrfs/file.c?id=580afd76e451deb6772d0507de580fb1df14da6c">Fix compressed checksum fsync log copies</a></td><td>ADS / RET</td></tr>
<tr><td><font size=+1><b>50: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs/btrfs/file.c?id=d397712bcc6a759a560fd247e6053ecae091f958">Fix checkpatch.pl warnings</a></td><td>RET</td></tr>
<tr><td><font size=+1><b>51: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs/btrfs/file.c?id=7237f1833601dcc435a64176c2c347ec4bd959f9">fix tree logs parallel sync</a></td><td>ADS / RET</td></tr>
<tr><td><font size=+1><b>52: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs/btrfs/file.c?id=2cfbd50b536c878e58ab3681c4e944fa3d99b415">check file pointer in btrfs_sync_file</a></td><td>ADS / RET</td></tr>
<tr><td><font size=+1><b>53: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs/btrfs/file.c?id=12fcfd22fe5bf4fe74710232098bc101af497995">tree logging unlink/rename fixes</a></td><td>FAU / RET</td></tr>
<tr><td><font size=+1><b>54: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs/btrfs/file.c?id=2ecb79239bcd04c9d410f4cdce16adb6840b19da">fix unprotected ->log_batch</a></td><td>ADS / RET / RACE</td></tr>
<tr><td><font size=+1><b>55: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs/btrfs/file.c?id=9f3959c53d57d010ae6f4205fbd0159cb7976a83">get right arguments for btrfs_wait_ordered_range</a></td><td>ADS</td></tr>
<tr><td><font size=+1><b>56: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs/btrfs/file.c?id=a0634be562c27ddee7c94bce4f765f8071244e07">don't leak transaction in btrfs_sync_file()</a></td><td>FAU / RET</td></tr>
<tr><td><font size=+1><b>57: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs/btrfs/file.c?id=0ef8b726075aa6931ddf1c16f5bae043eef184f9">return an error from btrfs_wait_ordered_range</a></td><td>RET</td></tr>
<tr><td><font size=+1><b>58: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs/btrfs/file.c?id=8b050d350c7846462a21e9e054c9154ede9b43cf">fix skipped error handle when log sync failed</a></td><td>FAU / ADS / CON</td></tr>
<tr><td><font size=+1><b>59: </b></font><a href="https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?h=v4.12-rc7&id=b05fd8742f6291b67571ad0fdad4da6b6eb98025">fix transaction leak during fsync call</a></td><td>FAU / CON</td></tr>
<tr><td><font size=+1><b>60: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs/btrfs/file.c?id=49dae1bc1c665817e434d01eefaa11967f618243">fix fsync data loss after a ranged fsync</a></td><td>ADS / RET</td></tr>
<tr><td><font size=+1><b>61: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs/btrfs/file.c?id=669249eea365dd32b793b58891c74281c0aac47e">fix fsync race leading to invalid data after log replay</a></td><td>RET / RACE</td></tr>
<tr><td><font size=+1><b>62: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs/btrfs/file.c?id=9dcbeed4d7e11e1dcf5e55475de3754f0855d1c2">fix signed overflows in btrfs_sync_file</a></td><td>FAU / CON</td></tr>
<tr><td><font size=+1><b>63: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs/btrfs/file.c?id=affc0ff902d539ebe9bba405d330410314f46e9f">fix race when checking if we can skip fsync'ing an inode</a></td><td>RET / RACE</td></tr>
<tr><td><font size=+1><b>64: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs/btrfs/file.c?id=de17e793b104d690e1d007dfc5cb6b4f649598ca">fix crash/invalid memory access on fsync when using overlayfs</a></td><td>ADS</td></tr>
<tr><td><font size=+1><b>65: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs/ubifs/file.c?id=7bbe5b5aa6d1e38af6f1fc866efc0aa461d73f19">use PAGE_CACHE_MASK correctly</a></td><td> Path State</td></tr>
<tr><td><font size=+1><b>66: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs/ubifs/file.c?id=54566b2c1594c2326a645a3551f9d989f7ba3c5e">symlink write_begin allocation context fix</a></td><td>ADS / Path State</td></tr>
<tr><td><font size=+1><b>67: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs/ubifs/file.c?id=f55aa59106b66cd547c8f296e0b3430ad76554c5">fix bug where page is marked uptodate when out of space</a></td><td>FAU / RET</td></tr>
<tr><td><font size=+1><b>68: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs/ubifs/file.c?id=2680d722bf2c5f75225dd9acb3ec9e5a9e2652f4">introduce new flag for RO due to errors</a></td><td>ADS / FAU</td></tr>
<tr><td><font size=+1><b>69: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs/ubifs/file.c?id=6ed09c34b7984a978a73a855f4c2e6662acc8bdb">fix assertion warning and refine comments</a></td><td>FAU / RET</td></tr>
<tr><td><font size=+1><b>70: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/fs/ubifs/file.c?id=09cbfeaf1a5a67bfb3201e0c83c810cecb2efa5a">get rid of PAGE_CACHE_* and page_cache_{get,release} macros</a></td><td>ADS / Path State</td></tr>
<tr><td><font size=+1><b>71: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/net/ipv4/tcp_input.c?id=314324121f9b94b2ca657a494cf2b9cb0e4a28cc">[TCP]: Fix stretch ACK performance killer when doing ucopy.</a></td><td>ADS / FAU</td></tr>
<tr><td><font size=+1><b>72: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/net/ipv4/tcp_input.c?id=55c97f3e990c1ff63957c64f6cb10711a09fd70e">[TCP]: Fix __tcp_push_pending_frames() 'nonagle' handling.</a></td><td> Path State</td></tr>
<tr><td><font size=+1><b>73: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/net/ipv4/tcp_input.c?id=15986e1aadbbf40a331cddd0470bb434d156431d">[TCP]: tcp_rcv_rtt_measure_ts() call in pure-ACK path is superfluous</a></td><td>CON</td></tr>
<tr><td><font size=+1><b>74: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/net/ipv4/tcp_input.c?id=9ae27e0adbf471c7a6b80102e38e1d5a346b3b38">tcp: Fix slab corruption with ipv6 and tcp6fuzz</a></td><td>CON / RET</td></tr>
<tr><td><font size=+1><b>75: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/net/ipv4/tcp_input.c?id=53240c208776d557dba9d7afedbcdbf512774c16">tcp: Fix possible double-ack w/ user dma</a></td><td>CON / RET / RACE</td></tr>
<tr><td><font size=+1><b>76: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/net/ipv4/tcp_input.c?id=59ea33a68a9083ac98515e4861c00e71efdc49a1">tcp: perform DMA to userspace only if there is a task waiting for it</a></td><td>CON /  Path State</td></tr>
<tr><td><font size=+1><b>77: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/net/ipv4/tcp_input.c?id=5d299f3d3c8a2fbc732b1bf03af36333ccec3130">net: ipv6: fix TCP early demux</a></td><td>ADS</td></tr>
<tr><td><font size=+1><b>78: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/net/ipv4/tcp_input.c?id=aab2b4bf224ef8358d262f95b568b8ad0cecf0a0">tcp: fix double-counted receiver RTT when leaving receiver fast path</a></td><td>CON / RET</td></tr>
<tr><td><font size=+1><b>79: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/net/ipv4/tcp_input.c?id=c995ae2259ee36caf48bbfacf40111998dacd4af">tcp: Change return value of tcp_rcv_established()</a></td><td>RET</td></tr>
<tr><td><font size=+1><b>80: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/net/ipv4/tcp_input.c?id=c10d9310edf5aa4a676991139d1a43ec7d87e56b">tcp: do not assume TCP code is non preemptible</a></td><td>CON / Path State</td></tr>
<tr><td><font size=+1><b>81: </b></font><a href="https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/drivers?id=bab6a9eac05360db25c81b0090f6b1195dd986cc">Fix setting initial MAC address</a></td><td> Path State</td></tr>
<tr><td><font size=+1><b>82: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/drivers/staging/rdma/hfi1?id=50b19729ced72cfa8bb1c44fed9203f395f13991">IB/hfi1: checking for NULL instead of IS_ERR</a></td><td>FAU</td></tr>
<tr><td><font size=+1><b>83: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/drivers/staging/rdma/hfi1?id=711e104ddca7b609889e1edf0a8482673ea4a7cc">staging/rdma/hfi1: fix panic in send engine</a></td><td>ADS / RET</td></tr>
<tr><td><font size=+1><b>84: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/drivers/infiniband/hw/hfi1?id=2aee309d3e01447c55fdf89cef05a0e2be372655">IB/hfi1: Fix deadlock with txreq allocation slow path</a></td><td>RET / RACE</td></tr>
<tr><td><font size=+1><b>85: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/drivers/net/ethernet/broadcom/bnx2x/bnx2x_cmn.c?id=e695a2dda1775dafc88174d2c0d71fab18db105a">bnx2x: dcb bit indices flags used as bits</a></td><td> Path State</td></tr>
<tr><td><font size=+1><b>86: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/drivers/net/ethernet/broadcom/bnx2x/bnx2x_cmn.c?id=a8f47eb701a562f6b5c81e2e0c143148915d7913">bnx2x: namespace and dead code cleanups</a></td><td> Path State / ADS</td></tr>
<tr><td><font size=+1><b>87: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/drivers/scsi/scsi_debug.c?id=6f3cbf552e0557a463ad421f07b2e873a608406f">[SCSI] scsi_debug: error processing</a></td><td>FAU</td></tr>
<tr><td><font size=+1><b>88: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/drivers/scsi/scsi_debug.c?id=44d9269481bb43df445adf464b06ff031e67d7ea">[SCSI] scsi_debug: Thin provisioning support</a></td><td>RET</td></tr>
<tr><td><font size=+1><b>89: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/drivers/scsi/scsi_debug.c?id=18a4d0a22ed6c54b67af7718c305cd010f09ddf8">[SCSI] Handle disk devices which can not process medium access commands</a></td><td>FAU</td></tr>
<tr><td><font size=+1><b>90: </b></font><a href="http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/drivers/scsi/scsi_debug.c?id=c2248fc974df7be55a5f6db6b6f99a90b749581b">scsi_debug: change SCSI command parser to table driven</a></td><td> Path State</td></tr>
   </tbody>
 </table>

### Chromium Fast Path Patches ###
<table>
 <thead>
     <tr>
     <td>Title</td>
     <td>Category</td>
    </tr>
    </thead>
   <tbody>
 <tr><td><font size=+1><b>1: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=624220">Improve performance of HTMLSelectElement by small hacks</a></td><td>CON / ADS</td></tr>
<tr><td><font size=+1><b>2: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=620142">Deleting many options from select element has become very slow.</a></td><td>CON / ADS</td></tr>
<tr><td><font size=+1><b>3: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=616176">RGB565 and RGB565_A1 doesn't work on Win8</a></td><td>CON / ADS</td></tr>
<tr><td><font size=+1><b>4: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=614765">Test failure oilpan_gc_times.key_silk_cases on android</a></td><td>FAU / CON</td></tr>
<tr><td><font size=+1><b>5: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=610287">Not invalidating all display items in slow-scrolling mode when filters are present on the HTML element</a></td><td>RET: </td></tr>
<tr><td><font size=+1><b>6: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=605502">ASSERTION FAILED: tagName.namespaceURI() == starAtom</a></td><td>CON:</td></tr>
<tr><td><font size=+1><b>7: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=604008">3.2% regression in page_cycler.top_10_mobile at 387300:387345</a></td><td>RET: </td></tr>
<tr><td><font size=+1><b>8: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=598094">Incorrect fast-path mapping for absolute-position object under relative-positioned anonymous block</a></td><td>CON: Missing conditions</td></tr>
<tr><td><font size=+1><b>9: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=597965">Fast-path and slow-path of paint invalidation rect mapping maps differently inside vertical-rl</a></td><td>IMV: Overlooking correlation</td></tr>
<tr><td><font size=+1><b>10: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=595324">SVG filter display error</a></td><td>IMV: Incorrectly passing variables</td></tr>
<tr><td><font size=+1><b>11: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=594516">Paint invalidation does not pixel-snap when crossing paintingRoot boundaries</a></td><td>FAU: Inappropriate fault handler</td></tr>
<tr><td><font size=+1><b>12: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=593872">6.2%-6.4% regression in rasterize_and_record_micro.top_25_smooth at 380376:380384</a></td><td>RET: Unexpected state</td></tr>
<tr><td><font size=+1><b>13: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=578306">Make it possible to build clang packages on the bots</a></td><td>IMV: Overlooking correlation</td></tr>
<tr><td><font size=+1><b>14: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=577989">HTMLSelectElement::selectOption is slow</a></td><td>ADS: Unnecessary member variables</td></tr>
<tr><td><font size=+1><b>15: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=573166">Chrome is slow on Mac OS when moving DIV above large SVG</a></td><td>CON: Wrong Condition</td></tr>
<tr><td><font size=+1><b>16: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=568196">cc should apply filters to original (unpadded) textures</a></td><td>RET: Wrong return</td></tr>
<tr><td><font size=+1><b>17: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=551484">Setting any automation forces slow path</a></td><td>CON: Missing conditions</td></tr>
<tr><td><font size=+1><b>18: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=530502">MemoryInfra: perform perf investigation to see the impact of heap profiler on blink</a></td><td>RET: Unexpected state</td></tr>
<tr><td><font size=+1><b>19: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=517188">Janky scrolling on tagesschau.de with Windows</a></td><td>IMV: Incorrectly passing variables</td></tr>
<tr><td><font size=+1><b>20: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=505410">Clean and common up parsing of &lt;color&gt; values</a></td><td>IMV: Overlooking correlation</td></tr>
<tr><td><font size=+1><b>21: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=504773">WebGL video test flakiness on Android</a></td><td>FAU: Missing fault handler</td></tr>
<tr><td><font size=+1><b>22: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=492572">Fast path when setting border-image-width to initial always fails</a></td><td>CON: Wrong Condition</td></tr>
<tr><td><font size=+1><b>23: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=491940">VK overscroll sometimes does not work with signin flow</a></td><td>FAU: Missing fault handler</td></tr>
<tr><td><font size=+1><b>24: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=490465">Compositor should early out if nothing is dirty after BeginMainFrame</a></td><td>FAU: Inappropriate fault handler</td></tr>
<tr><td><font size=+1><b>25: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=490023">Consider removing ElementData sharing</a></td><td>ADS: Collision</td></tr>
<tr><td><font size=+1><b>26: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=481926">[New Multicolumn] Spanner that also establishes a new multicol container not rendered properly</a></td><td>CON: Immature condition</td></tr>
<tr><td><font size=+1><b>27: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=481896">Breakpoints don't work in inline script with sourcemap</a></td><td>RET: Unexpected state</td></tr>
<tr><td><font size=+1><b>28: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=481663">[New Multicolumn] Assertion failure with spanner and backface-visibility:hidden</a></td><td>CON: Immature condition</td></tr>
<tr><td><font size=+1><b>29: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=477866">Embedding a PDF specified as a data: URL does not work</a></td><td>CON: Missing conditions</td></tr>
<tr><td><font size=+1><b>30: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=447917">Blink color parsing incorrectly allows \#ff0000 and rgb\(255\,0\,0\)</a></td><td>FAU: Missing fault handler</td></tr>
<tr><td><font size=+1><b>31: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=443055">Mongolian Script not rendered with vertical writing mode</a></td><td>RET: Wrong return</td></tr>
<tr><td><font size=+1><b>32: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=436145">limit CSS parser hashless-color and unitless-length quirks to only the properties that need them</a></td><td>ADS: Unnecessary member variables</td></tr>
<tr><td><font size=+1><b>33: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=424988">Complete implementation of css-syntax tokenizer</a></td><td>FAU: Missing fault handler</td></tr>
<tr><td><font size=+1><b>34: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=419270">Move fast-path parsing logic into a separate file</a></td><td>RET</td></tr>
<tr><td><font size=+1><b>35: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=406916">TouchEvent.preventDefault not honored if all touch handlers are removed from the page during event processing</a></td><td>IMV: Overwrite</td></tr>
<tr><td><font size=+1><b>36: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=398235">Security: possible another uninit memory with jpeg parsing</a></td><td>RET: Unexpected state</td></tr>
<tr><td><font size=+1><b>37: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=394130">Unify open_resource logic for SFI and non-SFI codepaths</a></td><td>CON: Missing conditions</td></tr>
<tr><td><font size=+1><b>38: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=391492">base::UTF8ToUTF16 is ~6x slower than blink::WebString::fromUTF8</a></td><td>ADS</td></tr>
<tr><td><font size=+1><b>39: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=387150">Calculate tile priorities in the raster/eviction iterators.</a></td><td>RET</td></tr>
<tr><td><font size=+1><b>40: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=383580">UVS (SV or IVS) is not supported even with a UVS-capable font</a></td><td>RET: Unexpected state</td></tr>
<tr><td><font size=+1><b>41: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=377921">Long Picture::Raster times on simple Google Search expansion cases</a></td><td>ADS</td></tr>
<tr><td><font size=+1><b>42: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=370664">Universal overflow scroll causes missing invalidations on jsfiddle.net</a></td><td>RET: Unexpected state</td></tr>
<tr><td><font size=+1><b>43: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=365507">ChromeOS login window issues on bots</a></td><td>RET: Unexpected state</td></tr>
<tr><td><font size=+1><b>44: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=362870">IE Popcorn benchmark slow due to rasterization and time-in-js</a></td><td>CON: Missing conditions</td></tr>
<tr><td><font size=+1><b>45: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=354431">Text uses slow paths?</a></td><td>ADS / CON</td></tr>
<tr><td><font size=+1><b>46: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=343802">data races in base::debug::TraceLog::GetCategoryGroupEnabledInternal</a></td><td>RET: Unexpected state</td></tr>
<tr><td><font size=+1><b>47: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=339141">ASSERTION FAILED: m_mapping.isEmpty() || isTopmostRenderView(m_mapping[0].m_renderer) in RenderGeometryMap</a></td><td>RET: Unexpected state</td></tr>
<tr><td><font size=+1><b>48: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=333012">Tighten the algorithms and repaint invalidations used by squashing</a></td><td>CON: Missing conditions</td></tr>
<tr><td><font size=+1><b>49: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=331903">Implement minimum overhead tracing method</a></td><td>RET</td></tr>
<tr><td><font size=+1><b>50: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=331254">Heap-buffer-overflow in WebCore::BisonCSSParser::parseValue</a></td><td>ADS: Inappropriate usage of structure</td></tr>
<tr><td><font size=+1><b>51: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=330088">Expand CSS transform parsing fast path to be less brittle</a></td><td>CON: Missing conditions</td></tr>
<tr><td><font size=+1><b>52: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=329566">touch-action is ignored for impl-thread scrolling</a></td><td>CON: Missing conditions</td></tr>
<tr><td><font size=+1><b>53: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=323962">tag#id selector queries are much slower than #id ones</a></td><td>CON: Missing conditions</td></tr>
<tr><td><font size=+1><b>54: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=323521">Divs with a border create 4 paint commands</a></td><td>CON: Missing conditions</td></tr>
<tr><td><font size=+1><b>55: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=322102">Blink should enable Kerning/Ligatures for the "fast path"</a></td><td>ADS: Not leveraging hardware features</td></tr>
<tr><td><font size=+1><b>56: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=321198">GitHub source container repaints-on-horizontal-scroll due to overflow-scroll fast path corner case</a></td><td>CON: Wrong Condition</td></tr>
<tr><td><font size=+1><b>57: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=316478">Horizontal scrolling on Android is janky</a></td><td>CON: Wrong Condition</td></tr>
<tr><td><font size=+1><b>58: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=313562">Changing left/top/bottom/right should set layer positions directly instead of doing layout</a></td><td>CON: Missing conditions</td></tr>
<tr><td><font size=+1><b>59: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=288574">Not connect to previous point when drawing ellipse</a></td><td>RET: Wrong return</td></tr>
<tr><td><font size=+1><b>60: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=270281">Touch flinging a div with accelerated scrolling shouldn't propagate scroll to parent container</a></td><td>CON: Missing conditions</td></tr>
<tr><td><font size=+1><b>61: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=259366">Security: JSON.stringify does not do cross context check.</a></td><td>ADS</td></tr>
<tr><td><font size=+1><b>62: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=251500">toDataURL() jpeg encoding path looks bad for canvas compression at high quality levels</a></td><td>RET</td></tr>
<tr><td><font size=+1><b>63: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=249357">Promote descendants of non-stacking context RenderLayers that use accelerated overflow scrolling</a></td><td>ADS</td></tr>
<tr><td><font size=+1><b>64: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=249354">Remove all corner cases from the overflow:scroll fast path on high-DPI</a></td><td>CON: Missing conditions</td></tr>
<tr><td><font size=+1><b>65: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=249349">Promote out-of-flow positioned descendants of accelerated scrolling layers.</a></td><td>ADS</td></tr>
<tr><td><font size=+1><b>66: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=245126">Add RenderFrame and RenderFrameHost</a></td><td>RET: Wrong return</td></tr>
<tr><td><font size=+1><b>67: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=237112">DCHECK failure while scrolling</a></td><td>IMV: Overlooking correlation</td></tr>
<tr><td><font size=+1><b>68: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=229245">previousSiblingSlow(node) == node-&gt;previousSibling() debug assertion failure</a></td><td>CON: Missing conditions</td></tr>
<tr><td><font size=+1><b>69: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=180046">An iframe can't be scrolled using touch after a fling is dispatched on its container</a></td><td>ADS: Missing context</td></tr>
<tr><td><font size=+1><b>70: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=180035">Fling gestures incorrectly bubble across iframe boundaries</a></td><td>ADS: Missing context</td></tr>
<tr><td><font size=+1><b>71: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=175670">gmail.com / who.ext.google.com is scrolling in the slow path on N10 / phone</a></td><td>CON: Wrong Condition</td></tr>
<tr><td><font size=+1><b>72: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=168099">Threaded uploads are slow on Galaxy Nexus (imagination GPU)</a></td><td>CON: Missing conditions</td></tr>
<tr><td><font size=+1><b>73: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=167321">gmail.com is not scrolling in the fast path</a></td><td>FAU: Missing fault handler</td></tr>
<tr><td><font size=+1><b>74: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=167201">Scrolling desktop Gmail on Android is broken</a></td><td>CON: Missing conditions</td></tr>
<tr><td><font size=+1><b>75: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=158688">Performance issue in tcmalloc with MaskPtr</a></td><td>CON: Wrong Condition</td></tr>
<tr><td><font size=+1><b>76: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=155043">Fixed-pos element leaves residue on desktop Youtube</a></td><td>RET: Unexpected state</td></tr>
<tr><td><font size=+1><b>77: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=151271">touchscreen fling targets the wrong document if you cross an iframe boundary</a></td><td>ADS: Missing context</td></tr>
<tr><td><font size=+1><b>78: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=146219">WebGL 512x512 and 128x128 texture rendering errors, 256x256 renders ok.</a></td><td>ADS</td></tr>
<tr><td><font size=+1><b>79: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=135004">Poor performance with Google+ Event Invites</a></td><td>RET: Wrong return</td></tr>
<tr><td><font size=+1><b>80: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=127781">Touch fling can target the wrong div (when not crossing an iframe boundary)</a></td><td>CON: Wrong Condition</td></tr>
<tr><td><font size=+1><b>81: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=120368">slashdot.org starts slow scrolling. Why?</a></td><td>RET: Wrong return</td></tr>
<tr><td><font size=+1><b>82: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=95640">Handle changes in video frame dimensions</a></td><td>ADS: Missing context</td></tr>
<tr><td><font size=+1><b>83: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=60384">fast/replaced/border-radius-clip.html is failing</a></td><td>CON: Missing conditions</td></tr>
<tr><td><font size=+1><b>84: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=51448">[Mac] Graphic-errors around the Toolbar-Icons</a></td><td>IMV: Incorrectly passing variables</td></tr>
<tr><td><font size=+1><b>85: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=43007">[10.5] Quicktime Plugin Crashes When Scrolling Window</a></td><td>CON: Missing conditions</td></tr>
<tr><td><font size=+1><b>86: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=40862">Chrome keeps hanging in a resize storm</a></td><td>ADS</td></tr>
<tr><td><font size=+1><b>87: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=39408">webkit box shadow with fixed positioning repaints incorrectly on scroll</a></td><td>CON: Wrong Condition</td></tr>
<tr><td><font size=+1><b>88: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=36661">Ctrl-1 gets queued while Ctrl-tab doesn't</a></td><td>ADS: Collision</td></tr>
<tr><td><font size=+1><b>89: </b></font><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=25692">Crash after ClosePageIgnoringUnloadEvents</a></td><td>RET: Wrong return</td></tr>
 </tbody>
 </table>
